export const LOG_IN = "log_ın"
export const LOG_OUT = "log_out"
export const SET_LOCALE = "set_locale"
export const ADD_TO_BASKET = "add_to_basket"
export const REMOVE_FROM_BASKET = "remove_from_basket"
export const SET_TOTAL = "set_total"